{{- if and (eq .Values.mode "statefulset") (.Values.configMap.create) (not .Values.defineCustomResource) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}-statefulset
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
data:
  relay: |
    {{- include "opentelemetry-collector.deploymentConfig" . | nindent 4 -}}
{{- end }}
