{{- if .Values.defineCustomResource -}}
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
      {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
      {{- end }}
  {{- end }}
spec:
  mode: {{ .Values.mode }}
  config: |
    {{- include "opentelemetry-collector.customresourceConfig" . | nindent 4 }}

  env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    {{- if .Values.presets.kubeletMetrics.enabled }}
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    {{- end }}
    {{- with .Values.extraEnvs }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}

  {{- if .Values.securityContext }}
  securityContext:
  {{- toYaml .Values.securityContext | nindent 4 }}
  {{- end }}

  hostNetwork: {{ .Values.hostNetwork }}

  {{- if .Values.extraVolumeMounts }}
  volumeMounts:
  {{- toYaml .Values.extraVolumeMounts | nindent 2 }}
  {{- end }}

  {{- if .Values.extraVolumes }}
  volumes:
  {{- toYaml .Values.extraVolumes | nindent 2 }}
  {{- end }}

{{- end }}
